import { KeyAttributes } from "src/presentation/KeyboardKey"

export const row1: KeyAttributes[] = [
  {
    code: 'Escape',
    primaryChar: 'esc',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-18 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'left',
      y: 'bottom',
    },
  },
  {
    code: 'F1',
    primaryChar: 'F1',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F2',
    primaryChar: 'F2',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F3',
    primaryChar: 'F3',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F4',
    primaryChar: 'F4',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F5',
    primaryChar: 'F5',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F6',
    primaryChar: 'F6',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F7',
    primaryChar: 'F7',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F8',
    primaryChar: 'F8',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F9',
    primaryChar: 'F9',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F10',
    primaryChar: 'F10',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F11',
    primaryChar: 'F11',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'F12',
    primaryChar: 'F12',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    // TODO: 多分keycodeにない
    code: 'power',
    primaryChar: '',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
];

export const row2: KeyAttributes[] = [
  {
    code: 'Backquote',
    primaryChar: '`',
    secondaryChar: '~',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit1',
    primaryChar: '1',
    secondaryChar: '!',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit2',
    primaryChar: '2',
    secondaryChar: '@',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit3',
    primaryChar: '3',
    secondaryChar: '#',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit4',
    primaryChar: '4',
    secondaryChar: '$',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit5',
    primaryChar: '5',
    secondaryChar: '%',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit6',
    primaryChar: '6',
    secondaryChar: '^',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit7',
    primaryChar: '7',
    secondaryChar: '&',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit8',
    primaryChar: '8',
    secondaryChar: '*',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit9',
    primaryChar: '9',
    secondaryChar: '(',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Digit0',
    primaryChar: '0',
    secondaryChar: ')',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Minus',
    primaryChar: '-',
    secondaryChar: '_',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Equal',
    primaryChar: '=',
    secondaryChar: '+',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Backspace',
    primaryChar: 'delete',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-18 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'right',
      y: 'bottom',
    },
  },
];

export const row3: KeyAttributes[] = [
  {
    code: 'Tab',
    primaryChar: 'tab',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-18 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'left',
      y: 'bottom',
    },
  },
  {
    code: 'KeyQ',
    primaryChar: 'Q',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyW',
    primaryChar: 'W',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyE',
    primaryChar: 'E',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyR',
    primaryChar: 'R',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyT',
    primaryChar: 'T',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyY',
    primaryChar: 'Y',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyU',
    primaryChar: 'U',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyI',
    primaryChar: 'I',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyO',
    primaryChar: 'O',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyP',
    primaryChar: 'P',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'BracketLeft',
    primaryChar: '[',
    secondaryChar: '{',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'BracketRight',
    primaryChar: ']',
    secondaryChar: '}',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Backslash',
    primaryChar: '\\',
    secondaryChar: '|',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
];

export const row4: KeyAttributes[] = [
  {
    code: 'CapsLock',
    primaryChar: 'caps lock',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-23 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'left',
      y: 'bottom',
    },
  },
  {
    code: 'KeyA',
    primaryChar: 'A',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyS',
    primaryChar: 'S',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyD',
    primaryChar: 'D',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyF',
    primaryChar: 'F',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyG',
    primaryChar: 'G',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyH',
    primaryChar: 'H',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyJ',
    primaryChar: 'J',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyK',
    primaryChar: 'K',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyL',
    primaryChar: 'L',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Semicolon',
    primaryChar: ';',
    secondaryChar: ':',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Quote',
    primaryChar: "'",
    secondaryChar: '"',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Enter',
    primaryChar: 'return',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-23 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'right',
      y: 'bottom',
    },
  },
];

export const row5: KeyAttributes[] = [
  {
    code: 'ShiftLeft',
    primaryChar: 'shift',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-30 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'left',
      y: 'bottom',
    },
  },
  {
    code: 'KeyZ',
    primaryChar: 'Z',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyX',
    primaryChar: 'X',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyC',
    primaryChar: 'C',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyV',
    primaryChar: 'V',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyB',
    primaryChar: 'B',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyN',
    primaryChar: 'N',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'KeyM',
    primaryChar: 'M',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Comma',
    primaryChar: ',',
    secondaryChar: '<',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Period',
    primaryChar: '.',
    secondaryChar: '>',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'Slash',
    primaryChar: '/',
    secondaryChar: '?',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xl',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'ShiftRight',
    primaryChar: 'shift',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-30 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'right',
      y: 'bottom',
    },
  },
];

export const row6: KeyAttributes[] = [
  {
    // TODO: keycodeにない
    code: 'Fn',
    primaryChar: 'fn',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'left',
      y: 'bottom',
    },
  },
  {
    code: 'ControlLeft',
    primaryChar: 'control',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'AltLeft',
    primaryChar: 'option',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'MetaLeft',
    primaryChar: 'command',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-16 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'Space',
    primaryChar: '',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-67 h-12',
    textSize: '',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'MetaRight',
    primaryChar: 'command',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-16 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'AltRight',
    primaryChar: 'option',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-12',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'bottom',
    },
  },
  {
    code: 'ArrowLeft',
    primaryChar: '◀︎',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-4',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'ArrowUp',
    primaryChar: '▲',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-4',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'ArrowDown',
    primaryChar: '▼',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-4',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
  {
    code: 'ArrowRight',
    primaryChar: '▶︎',
    isShiftPressed: false,
    isKeyPressed: false,
    keySize: 'w-12 h-4',
    textSize: 'text-xs',
    textPosition: {
      x: 'center',
      y: 'center',
    },
  },
];